### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by zoroya1** [yamin8000/Owl2#111]
Suddenly owl just shows pictures when one searches word like _horse_ and _unicorn_, words which doesn't contain pictures it doesn't retrieve anything.

**Comment by yamin8000** [comment]
> Suddenly owl just shows pictures when one searches word like _horse_ and _unicorn_, words which doesn't contain pictures it doesn't retrieve anything.

I just tried the latest build and everything works perfectly, there may be a device specific or network specific issue for you or it's a bug in the latest release.
![Screenshot_2023-04-14-12-05-16-747_io.github.yamin8000.owl.jpg](https://user-images.githubusercontent.com/5001708/231991084-8493e6b3-6711-4c19-b88f-e257226688c2.jpg)

![Screenshot_2023-04-14-12-05-27-657_io.github.yamin8000.owl.jpg](https://user-images.githubusercontent.com/5001708/231991083-d7a71c97-20b6-45af-8add-bf52869ae7c4.jpg)
