### ISSUE TITLE
Text highlighting

### ISSUE THREAD

**Issue by nvllz** [yamin8000/Owl2#141]
This would be very useful to allow text highlighting, especially when it comes to definition and example lines. This way we could share text directly from the app without having to switch apps.
Now, when you long tap on the definition text, it gets copied to the clipboard, and I think that's a nice feature. But I'd either make it copy to the clipboard on a single tap and highlight it on a long tap (so you can get a system context popup for easy sharing, etc.), or highlight the line text when you long tap the icon.

**Comment by yamin8000** [comment]
> This would be very useful to allow text highlighting, especially when it comes to definition and example lines. This way we could share text directly from the app without having to switch apps.
> Now, when you long tap on the definition text, it gets copied to the clipboard, and I think that's a nice feature. But I'd either make it copy to the clipboard on a single tap and highlight it on a long tap (so you can get a system context popup for easy sharing, etc.), or highlight the line text when you long tap the icon.

![Screenshot_2023-07-18-14-17-45-580_io.github.yamin8000.owl.jpg](https://github.com/yamin8000/Owl2/assets/5001708/13ea2540-f501-42bb-a4ce-2f6dcbc4e94a)

It seems text highlighting is not as good in Compose as I expected, however, it needs more investigation. So far it only provides only one button to copy, no option to share directly from the app.

**Comment by yamin8000** [comment]
> What about this? https://stackoverflow.com/questions/68956792/floating-toolbar-for-text-selection-jetpack-compose/68966424#68966424
> 
> If this doesn't work, maybe let's make some dialog popup when long tapping the icon with some options to copy, share etc..?

For now, I added a simple feature to make text selectable to copy, I may add that version later. I'll make a dedicated issue for that.
