### ISSUE TITLE
Support for receiving share actions

### ISSUE THREAD

**Issue by Siarune** [yamin8000/Owl2#76]
No rush or criticism, the app works well on its own.
I'm an avid reader and was hoping to use Owl as a quick dictionary lookup through Librera's "open in dictionary" action, which appears to operate through intents and app data sharing similar to [sharesheets](https://developer.android.com/training/sharing). I could be wrong, but most of the work would be to declare the necessary intents and a handler to take received data and use it for a search as normal.
I'll leave the implementation to you as that's entirely out of my scope and I'm probably wrong, but feel free to ask if you need any clarification.

**Comment by yamin8000** [comment]
> Librera's "open in dictionary" action

Do you mean this?
![photo_2022-11-11_09-03-16](https://user-images.githubusercontent.com/5001708/201270689-17dfa0c9-8cbe-46ad-8821-e51687005d29.jpg)
I did not know such a feature existed in the first place. I mean I'm aware of Intents but I wasn't aware of the specific Intent categories for dictionaries.


> I'll leave the implementation to you as that's entirely out of my scope and I'm probably wrong, but feel free to ask if you need any clarification.

No, you're not wrong. I should add your suggestion as a feature to the app.
Thank you.
