### ISSUE TITLE
wrong versionCode in v1.1.1

### ISSUE THREAD

**Issue by IzzySoft** [yamin8000/Owl2#87]
Looks like you forgot to increase `versionCode` before releasing v1.1.1 – APK (and `build.gradle`) still show `versionCode: 10` as they did with v1.1.0. Just to let you know :wink:

**Comment by yamin8000** [comment]
> Looks like you forgot to increase `versionCode` before releasing v1.1.1 – APK (and `build.gradle`) still show `versionCode: 10` as they did with v1.1.0. Just to let you know 😉

You're right. I forgot that.  
Thank you.
